# Análise Exploratória de Dados sobre Saúde Mental Estudantil (EDA)

## Objetivo

Realizar uma análise exploratória dos dados de saúde mental de estudantes,
identificando padrões, inconsistências e possíveis relações entre variáveis.

## Importação das bibliotecas

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Carregamento dos dados

In [3]:
df = pd.read_csv('../data/raw/MentalHealthSurvey.csv')

## Visualização inicial

In [4]:
df.head()

,gender,age,university,degree_level,degree_major,academic_year,cgpa,residential_status,campus_discrimination,sports_engagement,...,study_satisfaction,academic_workload,academic_pressure,financial_concerns,social_relationships,depression,anxiety,isolation,future_insecurity,stress_relief_activities
0,Male,20,PU,Undergraduate,Data Science,2nd year,3.0-3.5,Off-Campus,No,No Sports,...,5,4,5,4,3,2,1,1,2,"Religious Activities, Social Connections, Onli..."
1,Male,20,UET,Postgraduate,Computer Science,3rd year,3.0-3.5,Off-Campus,No,1-3 times,...,5,4,4,1,3,3,3,3,4,Online Entertainment
2,Male,20,FAST,Undergraduate,Computer Science,3rd year,2.5-3.0,Off-Campus,No,1-3 times,...,5,5,5,3,4,2,3,3,1,"Religious Activities, Sports and Fitness, Onli..."
3,Male,20,UET,Undergraduate,Computer Science,3rd year,2.5-3.0,On-Campus,No,No Sports,...,3,5,4,4,1,5,5,5,3,Online Entertainment
4,Female,20,UET,Undergraduate,Computer Science,3rd year,3.0-3.5,Off-Campus,Yes,No Sports,...,3,5,5,2,3,5,5,4,4,Online Entertainment

In [5]:
df.sample(5)

,gender,age,university,degree_level,degree_major,academic_year,cgpa,residential_status,campus_discrimination,sports_engagement,...,study_satisfaction,academic_workload,academic_pressure,financial_concerns,social_relationships,depression,anxiety,isolation,future_insecurity,stress_relief_activities
70,Male,22,UET,Undergraduate,Computer Science,3rd year,2.5-3.0,Off-Campus,No,No Sports,...,4,4,5,4,3,4,4,4,5,Religious Activities
0,Male,20,PU,Undergraduate,Data Science,2nd year,3.0-3.5,Off-Campus,No,No Sports,...,5,4,5,4,3,2,1,1,2,"Religious Activities, Social Connections, Onli..."
40,Female,19,PU,Undergraduate,Data Science,2nd year,2.5-3.0,Off-Campus,No,1-3 times,...,4,4,4,4,1,1,1,1,4,"Religious Activities, Social Connections, Onli..."
71,Male,20,UET,Undergraduate,Computer Science,3rd year,3.0-3.5,Off-Campus,No,7+ times,...,4,2,3,4,2,3,3,4,3,"Religious Activities, Sports and Fitness, Sleep"
55,Male,21,PU,Undergraduate,Data Science,2nd year,2.5-3.0,On-Campus,Yes,4-6 times,...,3,4,5,3,4,1,1,1,1,"Religious Activities, Social Connections"

## Exploração inicial

In [6]:
print(f'Linhas: {df.shape[0]}')
print(f'Colunas: {df.shape[1]}')

Linhas: 87
Colunas: 21

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gender                    87 non-null     str
 1   age                       87 non-null     int64
 2   university                87 non-null     str
 3   degree_level              87 non-null     str
 4   degree_major              87 non-null     str
 5   academic_year             87 non-null     str
 6   cgpa                      87 non-null     str
 7   residential_status        87 non-null     str
 8   campus_discrimination     87 non-null     str
 9   sports_engagement         87 non-null     str
 10  average_sleep             87 non-null     str
 11  study_satisfaction        87 non-null     int64
 12  academic_workload         87 non-null     int64
 13  academic_pressure         87 non-null     int64
 14  financial_concerns        87 non-null     int64
 15  social_relationships      87 non-null     int64
 16  depression                87 non-null     int64
 17  anxiety                   87 non-null     int64
 18  isolation                 87 non-null     int64
 19  future_insecurity         87 non-null     int64
 20  stress_relief_activities  87 non-null     str
dtypes: int64(10), str(11)
memory usage: 14.4 KB

In [8]:
df.describe(include='all')

,gender,age,university,degree_level,degree_major,academic_year,cgpa,residential_status,campus_discrimination,sports_engagement,...,study_satisfaction,academic_workload,academic_pressure,financial_concerns,social_relationships,depression,anxiety,isolation,future_insecurity,stress_relief_activities
count,87,87.000000,87,87,87,87,87,87,87,87,...,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87
unique,2,NaN,9,2,4,4,6,2,2,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38
top,Male,NaN,PU,Undergraduate,Data Science,1st year,3.0-3.5,Off-Campus,No,No Sports,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Religious Activities
freq,63,NaN,56,85,41,34,27,65,65,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
mean,NaN,19.942529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.931034,3.885057,3.781609,3.390805,2.781609,3.218391,3.218391,3.241379,3.011494,NaN
std,NaN,1.623636,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.043174,0.854880,1.125035,1.400634,1.175578,1.367609,1.297809,1.405682,1.385089,NaN
min,NaN,17.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN
25%,NaN,19.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.000000,3.000000,3.000000,2.500000,2.000000,2.000000,2.000000,2.000000,2.000000,NaN
50%,NaN,20.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.000000,4.000000,4.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,NaN
75%,NaN,21.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,4.500000,5.000000,5.000000,4.000000,4.000000,4.000000,4.500000,4.000000,NaN
max,NaN,26.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,NaN

## Qualidade dos dados

### Valores nulos

In [9]:
df.isnull().sum()

gender                      0
age                         0
university                  0
degree_level                0
degree_major                0
academic_year               0
cgpa                        0
residential_status          0
campus_discrimination       0
sports_engagement           0
average_sleep               0
study_satisfaction          0
academic_workload           0
academic_pressure           0
financial_concerns          0
social_relationships        0
depression                  0
anxiety                     0
isolation                   0
future_insecurity           0
stress_relief_activities    0
dtype: int64

### Linhas duplicadas

In [10]:
print(f'Número de linhas duplicadas: {df.duplicated().sum()}')

Número de linhas duplicadas: 0

 ## Processamento e limpeza dos dados

In [11]:
from src.preprocessing import process_data

In [12]:
df = process_data(df)

## Verificação pós-processamento

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gender                    87 non-null     str
 1   age                       87 non-null     int64
 2   university                87 non-null     str
 3   degree_level              87 non-null     str
 4   degree_major              87 non-null     str
 5   academic_year             87 non-null     int64
 6   cgpa                      87 non-null     float64
 7   residential_status        87 non-null     str
 8   campus_discrimination     87 non-null     str
 9   sports_engagement         87 non-null     str
 10  average_sleep             87 non-null     float64
 11  study_satisfaction        87 non-null     int64
 12  academic_workload         87 non-null     int64
 13  academic_pressure         87 non-null     int64
 14  financial_concerns        87 non-null     int64
 15  social_relationships      87 non-null     int64
 16  depression                87 non-null     int64
 17  anxiety                   87 non-null     int64
 18  isolation                 87 non-null     int64
 19  future_insecurity         87 non-null     int64
 20  stress_relief_activities  87 non-null     str
dtypes: float64(2), int64(11), str(8)
memory usage: 14.4 KB

In [14]:
df.head()

,gender,age,university,degree_level,degree_major,academic_year,cgpa,residential_status,campus_discrimination,sports_engagement,...,study_satisfaction,academic_workload,academic_pressure,financial_concerns,social_relationships,depression,anxiety,isolation,future_insecurity,stress_relief_activities
0,Male,20,PU,Undergraduate,Data Science,2,3.25,Off-Campus,No,No Sports,...,5,4,5,4,3,2,1,1,2,"Religious Activities, Social Connections, Onli..."
1,Male,20,UET,Postgraduate,Computer Science,3,3.25,Off-Campus,No,1-3 times,...,5,4,4,1,3,3,3,3,4,Online Entertainment
2,Male,20,FAST,Undergraduate,Computer Science,3,2.75,Off-Campus,No,1-3 times,...,5,5,5,3,4,2,3,3,1,"Religious Activities, Sports and Fitness, Onli..."
3,Male,20,UET,Undergraduate,Computer Science,3,2.75,On-Campus,No,No Sports,...,3,5,4,4,1,5,5,5,3,Online Entertainment
4,Female,20,UET,Undergraduate,Computer Science,3,3.25,Off-Campus,Yes,No Sports,...,3,5,5,2,3,5,5,4,4,Online Entertainment

In [15]:
df.describe(include='all')

,gender,age,university,degree_level,degree_major,academic_year,cgpa,residential_status,campus_discrimination,sports_engagement,...,study_satisfaction,academic_workload,academic_pressure,financial_concerns,social_relationships,depression,anxiety,isolation,future_insecurity,stress_relief_activities
count,87,87.000000,87,87,87,87.000000,87.000000,87,87,87,...,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87
unique,2,NaN,9,2,4,NaN,NaN,2,2,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38
top,Male,NaN,PU,Undergraduate,Data Science,NaN,NaN,Off-Campus,No,No Sports,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Religious Activities
freq,63,NaN,56,85,41,NaN,NaN,65,65,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
mean,NaN,19.942529,NaN,NaN,NaN,2.160920,3.011494,NaN,NaN,NaN,...,3.931034,3.885057,3.781609,3.390805,2.781609,3.218391,3.218391,3.241379,3.011494,NaN
std,NaN,1.623636,NaN,NaN,NaN,1.076963,0.893214,NaN,NaN,NaN,...,1.043174,0.854880,1.125035,1.400634,1.175578,1.367609,1.297809,1.405682,1.385089,NaN
min,NaN,17.000000,NaN,NaN,NaN,1.000000,0.000000,NaN,NaN,NaN,...,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN
25%,NaN,19.000000,NaN,NaN,NaN,1.000000,2.750000,NaN,NaN,NaN,...,3.000000,3.000000,3.000000,2.500000,2.000000,2.000000,2.000000,2.000000,2.000000,NaN
50%,NaN,20.000000,NaN,NaN,NaN,2.000000,3.250000,NaN,NaN,NaN,...,4.000000,4.000000,4.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,NaN
75%,NaN,21.000000,NaN,NaN,NaN,3.000000,3.750000,NaN,NaN,NaN,...,5.000000,4.500000,5.000000,5.000000,4.000000,4.000000,4.000000,4.500000,4.000000,NaN
max,NaN,26.000000,NaN,NaN,NaN,4.000000,3.750000,NaN,NaN,NaN,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,NaN